update

diff --git a/.github/workflows/create_new_release.yml b/.github/workflows/create_new_release.yml
--- a/.github/workflows/create_new_release.yml
+++ b/.github/workflows/create_new_release.yml
@@ -17,8 +17,14 @@ jobs:
         env:
           BRANCH: ${{ github.event.inputs.release_branch_name }}
         run: |
-          set -e
-          . .githooks/common.bash
+          check_format_release_branch() {
+            branch="$1"
+            match_count=$(echo ${branch} | grep -o -P "${regexp_release_branch}" | wc -l)
+            if [[ ${match_count} != 1 ]]; then
+              >&2 echo "ERROR: release branch is not formatted"; return 1
+            fi
+            return 0
+          }
           $(check_format_release_branch "${BRANCH}")
       - name: Create new release branch
         uses: peterjgrainger/action-create-branch@v2.0.1
